//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace YTPPlusPlus.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("C:/Program Files (x86)/VideoLAN/VLC")]
        public string VLC {
            get {
                return ((string)(this["VLC"]));
            }
            set {
                this["VLC"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Dark")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_RandomSound {
            get {
                return ((bool)(this["effect_RandomSound"]));
            }
            set {
                this["effect_RandomSound"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_RandomSoundMute {
            get {
                return ((bool)(this["effect_RandomSoundMute"]));
            }
            set {
                this["effect_RandomSoundMute"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_Reverse {
            get {
                return ((bool)(this["effect_Reverse"]));
            }
            set {
                this["effect_Reverse"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_SpeedUp {
            get {
                return ((bool)(this["effect_SpeedUp"]));
            }
            set {
                this["effect_SpeedUp"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_SlowDown {
            get {
                return ((bool)(this["effect_SlowDown"]));
            }
            set {
                this["effect_SlowDown"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_Chorus {
            get {
                return ((bool)(this["effect_Chorus"]));
            }
            set {
                this["effect_Chorus"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_Vibrato {
            get {
                return ((bool)(this["effect_Vibrato"]));
            }
            set {
                this["effect_Vibrato"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_HighPitch {
            get {
                return ((bool)(this["effect_HighPitch"]));
            }
            set {
                this["effect_HighPitch"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_LowPitch {
            get {
                return ((bool)(this["effect_LowPitch"]));
            }
            set {
                this["effect_LowPitch"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_Dance {
            get {
                return ((bool)(this["effect_Dance"]));
            }
            set {
                this["effect_Dance"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool effect_Squidward {
            get {
                return ((bool)(this["effect_Squidward"]));
            }
            set {
                this["effect_Squidward"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PluginTest {
            get {
                return ((bool)(this["PluginTest"]));
            }
            set {
                this["PluginTest"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool InsertTransitions {
            get {
                return ((bool)(this["InsertTransitions"]));
            }
            set {
                this["InsertTransitions"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool InsertIntro {
            get {
                return ((bool)(this["InsertIntro"]));
            }
            set {
                this["InsertIntro"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool InsertOutro {
            get {
                return ((bool)(this["InsertOutro"]));
            }
            set {
                this["InsertOutro"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("20")]
        public int Clips {
            get {
                return ((int)(this["Clips"]));
            }
            set {
                this["Clips"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("640")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("480")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.2")]
        public decimal MinStreamDur {
            get {
                return ((decimal)(this["MinStreamDur"]));
            }
            set {
                this["MinStreamDur"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.4")]
        public decimal MaxStreamDur {
            get {
                return ((decimal)(this["MaxStreamDur"]));
            }
            set {
                this["MaxStreamDur"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("resources\\intro.mp4")]
        public string Intro {
            get {
                return ((string)(this["Intro"]));
            }
            set {
                this["Intro"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("resources\\outro.mp4")]
        public string Outro {
            get {
                return ((string)(this["Outro"]));
            }
            set {
                this["Outro"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ffmpeg.exe")]
        public string FFmpeg {
            get {
                return ((string)(this["FFmpeg"]));
            }
            set {
                this["FFmpeg"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ffprobe.exe")]
        public string FFprobe {
            get {
                return ((string)(this["FFprobe"]));
            }
            set {
                this["FFprobe"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("magick")]
        public string Magick {
            get {
                return ((string)(this["Magick"]));
            }
            set {
                this["Magick"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("sources\\")]
        public string Sources {
            get {
                return ((string)(this["Sources"]));
            }
            set {
                this["Sources"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("temp\\")]
        public string Temp {
            get {
                return ((string)(this["Temp"]));
            }
            set {
                this["Temp"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("sounds\\")]
        public string Sounds {
            get {
                return ((string)(this["Sounds"]));
            }
            set {
                this["Sounds"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("music\\")]
        public string Music {
            get {
                return ((string)(this["Music"]));
            }
            set {
                this["Music"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("resources\\")]
        public string Resources {
            get {
                return ((string)(this["Resources"]));
            }
            set {
                this["Resources"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("sources\\")]
        public string TransitionDir {
            get {
                return ((string)(this["TransitionDir"]));
            }
            set {
                this["TransitionDir"] = value;
            }
        }
    }
}
